/**
 * Liest docs/legal/studio/*.{vN}.md und schreibt src/generated/studioLegalTemplates.ts.
 * Hash = SHA-256 nach normalize_legal_text (wie yogaflow_private.hash_legal_text).
 *
 * Vorlagen-Dateien sind unveränderlich, sobald eine Version freigegeben wurde.
 * Änderungen nur als neue Datei (agb.v2.md …). Freigegebene Hashes: STUDIO_LEGAL_TEMPLATE_RELEASES.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function normalizeLegalText(text) {
  return String(text)
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n+$/g, '')
    .concat('\n');
}

export function hashLegalText(text) {
  return createHash('sha256').update(normalizeLegalText(text), 'utf8').digest('hex');
}

/** Dateiname-Suffix vN → Kalender-Version (DB / Freigabe). */
const FILE_VERSION_DATES = {
  1: '2026-10-05',
  2: '2026-10-08',
};

const KIND_FILES = {
  imprint: 'impressum',
  terms: 'agb',
  privacy: 'datenschutz',
};

const ACCEPTANCE_DOCS = {
  terms: 'studio_terms_tpl',
  privacy: 'studio_privacy_tpl',
};

function isMainModule() {
  const self = fileURLToPath(import.meta.url);
  const invoked = process.argv[1] ? join(process.cwd(), process.argv[1]) : '';
  return self === invoked || self.replace(/\\/g, '/') === String(invoked).replace(/\\/g, '/');
}

function loadKindReleases(kind) {
  const prefix = KIND_FILES[kind];
  const dir = join(root, 'docs/legal/studio');
  const files = readdirSync(dir)
    .filter((f) => new RegExp(`^${prefix}\\.v\\d+\\.md$`).test(f))
    .sort((a, b) => {
      const na = Number(a.match(/\.v(\d+)\.md$/)[1]);
      const nb = Number(b.match(/\.v(\d+)\.md$/)[1]);
      return na - nb;
    });
  if (files.length === 0) {
    throw new Error(`Keine Vorlagen für ${kind} (${prefix}.vN.md)`);
  }
  return files.map((file) => {
    const n = Number(file.match(/\.v(\d+)\.md$/)[1]);
    const version = FILE_VERSION_DATES[n];
    if (!version) {
      throw new Error(`FILE_VERSION_DATES fehlt für v${n} (${file})`);
    }
    const body = readFileSync(join(dir, file), 'utf8');
    const contentHash = hashLegalText(body);
    console.log(`${file}: ${contentHash} (${version})`);
    return { file, version, contentHash, body, n };
  });
}

if (isMainModule()) {
  const releases = {
    imprint: loadKindReleases('imprint'),
    terms: loadKindReleases('terms'),
    privacy: loadKindReleases('privacy'),
  };

  const current = {
    imprint: releases.imprint[releases.imprint.length - 1],
    terms: releases.terms[releases.terms.length - 1],
    privacy: releases.privacy[releases.privacy.length - 1],
  };

  const VERSION = current.terms.version;
  if (current.privacy.version !== VERSION) {
    console.warn(
      `Hinweis: terms current ${current.terms.version} ≠ privacy ${current.privacy.version}`,
    );
  }

  const sub = JSON.parse(readFileSync(join(root, 'docs/legal/subprocessors.json'), 'utf8'));

  const tsPath = join(root, 'src/generated/studioLegalTemplates.ts');
  mkdirSync(dirname(tsPath), { recursive: true });

  const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  function releaseLiteral(kind) {
    return releases[kind]
      .map(
        (r) => `  {
    file: ${JSON.stringify(r.file)},
    version: ${JSON.stringify(r.version)},
    contentHash: ${JSON.stringify(r.contentHash)},
    body: \`${esc(r.body)}\`,
  }`,
      )
      .join(',\n');
  }

  const ts = `/* GENERATED by scripts/generate_studio_legal_templates.mjs — do not edit */
export const STUDIO_LEGAL_TEMPLATE_VERSION = ${JSON.stringify(VERSION)} as const;

export type StudioLegalTemplateKind = 'imprint' | 'terms' | 'privacy';

export type StudioLegalTemplateRelease = {
  file: string;
  version: string;
  contentHash: string;
  body: string;
};

/** Alle freigegebenen Vorlagen-Versionen (unveränderlich). CI prüft Hashes. */
export const STUDIO_LEGAL_TEMPLATE_RELEASES: Record<
  StudioLegalTemplateKind,
  readonly StudioLegalTemplateRelease[]
> = {
  imprint: [
${releaseLiteral('imprint')}
  ],
  terms: [
${releaseLiteral('terms')}
  ],
  privacy: [
${releaseLiteral('privacy')}
  ],
} as const;

export const STUDIO_LEGAL_TEMPLATE_HASHES = {
  imprint: ${JSON.stringify(current.imprint.contentHash)},
  terms: ${JSON.stringify(current.terms.contentHash)},
  privacy: ${JSON.stringify(current.privacy.contentHash)},
} as const;

/** Freigabe-Dokumente in legal_document_versions / legal_acceptances (aktuell) */
export const STUDIO_LEGAL_ACCEPTANCE_DOCS = {
  terms: {
    document: 'studio_terms_tpl' as const,
    version: ${JSON.stringify(current.terms.version)},
    contentHash: ${JSON.stringify(current.terms.contentHash)},
  },
  privacy: {
    document: 'studio_privacy_tpl' as const,
    version: ${JSON.stringify(current.privacy.version)},
    contentHash: ${JSON.stringify(current.privacy.contentHash)},
  },
} as const;

export const STUDIO_LEGAL_SUBPROCESSORS = ${JSON.stringify(sub, null, 2)} as const;

/** Aktuelle Vorlagen-Bodies (neueste Version je Art). */
export const STUDIO_LEGAL_TEMPLATES: Record<StudioLegalTemplateKind, string> = {
  imprint: STUDIO_LEGAL_TEMPLATE_RELEASES.imprint[STUDIO_LEGAL_TEMPLATE_RELEASES.imprint.length - 1].body,
  terms: STUDIO_LEGAL_TEMPLATE_RELEASES.terms[STUDIO_LEGAL_TEMPLATE_RELEASES.terms.length - 1].body,
  privacy: STUDIO_LEGAL_TEMPLATE_RELEASES.privacy[STUDIO_LEGAL_TEMPLATE_RELEASES.privacy.length - 1].body,
};

export function findStudioLegalTemplateRelease(
  kind: StudioLegalTemplateKind,
  opts?: { version?: string | null; contentHash?: string | null },
): StudioLegalTemplateRelease {
  const list = STUDIO_LEGAL_TEMPLATE_RELEASES[kind];
  if (opts?.contentHash) {
    const byHash = list.find((r) => r.contentHash === opts.contentHash);
    if (byHash) return byHash;
  }
  if (opts?.version) {
    const byVer = list.find((r) => r.version === opts.version);
    if (byVer) return byVer;
  }
  return list[list.length - 1];
}
`;

  writeFileSync(tsPath, ts, 'utf8');
  console.log('wrote', tsPath);
  console.log(`current version: ${VERSION}`);
  console.log(`-- SQL seed hashes:`);
  for (const kind of ['terms', 'privacy']) {
    const doc = ACCEPTANCE_DOCS[kind];
    const r = current[kind];
    console.log(`-- ${doc}: ${r.version} ${r.contentHash}`);
  }
}
