/**
 * Liest docs/legal/studio/*.v1.md und schreibt src/generated/studioLegalTemplates.ts.
 * Hash = SHA-256 nach normalize_legal_text (wie yogaflow_private.hash_legal_text).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function normalizeLegalText(text) {
  return String(text)
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n+$/g, '')
    .concat('\n');
}

export function hashLegalText(text) {
  return createHash('sha256').update(normalizeLegalText(text), 'utf8').digest('hex');
}

const TEMPLATES = [
  { kind: 'imprint', file: 'impressum.v1.md', document: null },
  { kind: 'terms', file: 'agb.v1.md', document: 'studio_terms_tpl' },
  { kind: 'privacy', file: 'datenschutz.v1.md', document: 'studio_privacy_tpl' },
];

const VERSION = '2026-10-05';

const out = {
  version: VERSION,
  templates: {},
  documents: {},
};

for (const t of TEMPLATES) {
  const body = readFileSync(join(root, 'docs/legal/studio', t.file), 'utf8');
  const hash = hashLegalText(body);
  out.templates[t.kind] = { file: t.file, version: VERSION, contentHash: hash, body };
  if (t.document) {
    out.documents[t.document] = { version: VERSION, contentHash: hash };
  }
  console.log(`${t.file}: ${hash}`);
}

const sub = JSON.parse(readFileSync(join(root, 'docs/legal/subprocessors.json'), 'utf8'));

const tsPath = join(root, 'src/generated/studioLegalTemplates.ts');
mkdirSync(dirname(tsPath), { recursive: true });

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const ts = `/* GENERATED by scripts/generate_studio_legal_templates.mjs — do not edit */
export const STUDIO_LEGAL_TEMPLATE_VERSION = ${JSON.stringify(VERSION)} as const;

export type StudioLegalTemplateKind = 'imprint' | 'terms' | 'privacy';

export const STUDIO_LEGAL_TEMPLATE_HASHES = {
  imprint: ${JSON.stringify(out.templates.imprint.contentHash)},
  terms: ${JSON.stringify(out.templates.terms.contentHash)},
  privacy: ${JSON.stringify(out.templates.privacy.contentHash)},
} as const;

/** Freigabe-Dokumente in legal_document_versions / legal_acceptances */
export const STUDIO_LEGAL_ACCEPTANCE_DOCS = {
  terms: {
    document: 'studio_terms_tpl' as const,
    version: ${JSON.stringify(VERSION)},
    contentHash: ${JSON.stringify(out.documents.studio_terms_tpl.contentHash)},
  },
  privacy: {
    document: 'studio_privacy_tpl' as const,
    version: ${JSON.stringify(VERSION)},
    contentHash: ${JSON.stringify(out.documents.studio_privacy_tpl.contentHash)},
  },
} as const;

export const STUDIO_LEGAL_SUBPROCESSORS = ${JSON.stringify(sub, null, 2)} as const;

export const STUDIO_LEGAL_TEMPLATES: Record<StudioLegalTemplateKind, string> = {
  imprint: \`${esc(out.templates.imprint.body)}\`,
  terms: \`${esc(out.templates.terms.body)}\`,
  privacy: \`${esc(out.templates.privacy.body)}\`,
};
`;

writeFileSync(tsPath, ts, 'utf8');
console.log('wrote', tsPath);

// SQL seed snippet for migration (stdout)
console.log('\n-- SQL seed hashes:');
for (const [doc, meta] of Object.entries(out.documents)) {
  console.log(`-- ${doc}: ${meta.contentHash}`);
}
